# DNNs with Keras

nach dem Tut aus: https://github.com/llSourcell/keras_explained/blob/master/gentext.py

In [1]:
from __future__ import print_function
from keras.callbacks import LambdaCallback
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM
from keras.optimizers import RMSprop
from keras.utils.data_utils import get_file
import numpy as np
import random
import sys
import io

Using TensorFlow backend.


# Task 1: retrieve data

Load your data! 

In [2]:
#path = get_file('bundestag.txt', origin='https://www.bundestag.de/blob/569484/7b0f24562fb8ddcbc26f6b4c0591d8f8/19050-data.xml')
#text = io.open("trump.txt", encoding='utf-8').read().lower()

text = " hallo. " 
print('corpus length:', len(text))



corpus length: 8


## Task: Preprocessing
generate classes. 


In [3]:
text[:1000]

' hallo. '

In [4]:
chars = sorted(list(set(text)))
print('total chars:', len(chars))

total chars: 6


In [5]:
chars = chars[2:15]

In [6]:
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

In [7]:
char_indices

{'a': 0, 'h': 1, 'l': 2, 'o': 3}

In [8]:
# cut the text in semi-redundant sequences of maxlen characters
maxlen = 4
step = 1
sentences = []
next_chars = []

In [9]:
for i in range(0, len(text) - maxlen, step):
    sentences.append(text[i: i + maxlen])
    next_chars.append(text[i + maxlen])
print('nb sequences:', len(sentences))

nb sequences: 4


In [10]:
for idx in range(len(sentences)):
    print(sentences[idx], ":" , next_chars[idx])

 hal : l
hall : o
allo : .
llo. :  


In [11]:
sentences = ["hall", "allo", "lloh", "loha", "ohal"]
next_chars = ["o", "h", "a", "l", "l"]

In [12]:
print('Vectorization...')
x = np.zeros((len(sentences), maxlen, len(chars)))
y = np.zeros((len(sentences), len(chars)))
for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        x[i, t, char_indices[char]] = 1
    y[i, char_indices[next_chars[i]]] = 1

Vectorization...


In [13]:
x.shape
# seq

(5, 4, 4)

In [14]:
chars[:]

['a', 'h', 'l', 'o']

In [15]:
x[0]

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [16]:
y[0]

array([ 0.,  0.,  0.,  1.])

In [17]:
# input
print(y[0], "->")
print(len(x[0]))
print()
print(len(x))

[ 0.  0.  0.  1.] ->
4

5


In [18]:
# build the model: a LSTM
print('Build model...')
model = Sequential()
model.add(LSTM(128, input_shape=(maxlen, len(chars))))
#model.add(Activation('relu'))
#model.add(LSTM(128))
#model.add(Activation('relu'))          
model.add(Dense(len(chars)))
model.add(Activation('softmax'))
model.summary()

optimizer = RMSprop(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=optimizer)

Build model...
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 128)               68096     
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 516       
_________________________________________________________________
activation_1 (Activation)    (None, 4)                 0         
Total params: 68,612
Trainable params: 68,612
Non-trainable params: 0
_________________________________________________________________


In [19]:
#model = Sequential()
#model.add(LSTM(128, input_shape=(maxlen, len(chars))))
#model.add(Dense(len(chars)))
#model.add(Activation('softmax'))

#model.summary()
#optimizer = RMSprop(lr=0.01)
#model.compile(loss='categorical_crossentropy', optimizer=optimizer)

In [20]:
# DAS WIRD MITGEGEBEN111!!!!

def sample(preds, temperature=1.0):
    # helper function to sample an index from a probability array
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)

In [21]:
#

In [22]:
def on_epoch_end(epoch, logs):
    # Function invoked at end of each epoch. Prints generated text.
    print()
    print('----- Generating text after Epoch: %d' % epoch)

    start_index = random.randint(0, len(text) - maxlen - 1)
    for diversity in [0.1,]:
        print('----- diversity:', diversity)

        generated = ''
        #sentence = text[start_index: start_index + maxlen]
        sentence = "hall"
        generated += sentence
        print('----- Generating with seed: "' + sentence + '"')
        sys.stdout.write(generated)

        for i in range(400):
            x_pred = np.zeros((1, maxlen, len(chars)))
            for t, char in enumerate(sentence):
                x_pred[0, t, char_indices[char]] = 1.

            preds = model.predict(x_pred, verbose=0)[0]
            next_index = sample(preds, diversity)
            next_char = indices_char[next_index]

            generated += next_char
            sentence = sentence[1:] + next_char

            sys.stdout.write(next_char)
            sys.stdout.flush()
        print()

In [23]:
print_callback = LambdaCallback(on_epoch_end=on_epoch_end)

In [24]:
model.fit(x, y,
          batch_size=128,
          epochs=3,
          callbacks=[print_callback])

Epoch 1/3
5/5 [==============================] - 1s 265ms/step - loss: 1.3876

----- Generating text after Epoch: 0
----- diversity: 0.1
----- Generating with seed: "hall"
halllllllllllllllllhllllllllllllhlllllllholllllllllllhlllllllllollllllllllllllllallllllllllllllllllllllllllllllllllllllohllllllllllllhllllllllllllolllllllllllllllllllllllllllllllllllollllllllllllllllollllllllllllllllllllllalllllllhllllllllllllllholllllllllllllllllllllllllllllllllllllllllllllhlllllllohllllllllllllllllllllllhllllllllllllllloallllllllllllllllllalllllllllohllllllolllllllhlllllllllllllllll
Epoch 2/3
5/5 [==============================] - 0s 2ms/step - loss: 1.0912

----- Generating text after Epoch: 1
----- diversity: 0.1
----- Generating with seed: "hall"
hallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohallohal